"""Generate the fictional demo dataset for the hosted Tessera demo.

Persona: 'Alex at Acme Payments' — a developer using Claude Code (mostly),
some Codex, occasional Gemini CLI across a Stripe checkout integration,
a FastAPI backend, mobile app, and internal tooling.

Run from this directory:
    python generate.py

Outputs:
    narratives/<session_id>.json  — 10 per-session narratives
    synthesis.json                 — cross-session synthesis output
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

OUT = Path(__file__).parent
NARRATIVES_DIR = OUT / "narratives"
NARRATIVES_DIR.mkdir(exist_ok=True)


def obs_key(title: str, claim: str) -> str:
    seed = (title + "|" + claim)[:400]
    return hashlib.sha1(seed.encode()).hexdigest()[:10]


# ---------- 10 fictional per-session narratives ----------

SESSIONS = [
    {
        "session_id": "claude:8a1b9c12-d3e4-4f56-789a-bcdef0123401",
        "agent": "claude",
        "project_path": "/Users/alex/work/acme-checkout",
        "project_label": "work/acme-checkout",
        "git_branch_last": "feat/stripe-webhooks-v3",
        "models_used": ["claude-sonnet-4-6", "claude-haiku-4-5"],
        "primary_model": "claude-sonnet-4-6",
        "started_at": "2026-04-22T09:14:12Z",
        "ended_at": "2026-04-22T11:48:33Z",
        "wall_clock_minutes": 154.3,
        "active_minutes": 87.5,
        "primary_burst_minutes": 52.1,
        "longest_idle_minutes": 14.2,
        "bursts": 3,
        "events_per_active_minute": 8.4,
        "time_of_day_buckets": {"morning": 412, "afternoon": 322, "evening": 0, "night": 0},
        "weekday": "Wednesday",
        "event_count": 734,
        "tool_call_count": 287,
        "user_turn_count": 19,
        "subagent_count": 2,
        "subagent_event_count": 142,
        "subagent_types_spawned": {"explore": 1, "general-purpose": 1},
        "tool_call_distribution": {"Bash": 84, "Read": 71, "Edit": 38, "Grep": 31, "Glob": 22},
        "tool_category_distribution": {"shell": 84, "read": 124, "write": 38, "delegation": 12, "other": 29},
        "tool_error_rate": 0.061,
        "tool_error_classes": {"tool_error": 17, "permission_denied": 1},
        "most_repeated_tool_call": {"tool": "Bash", "input_hash": "a1b2c3d4e5", "count": 8, "input_preview": "pytest tests/test_webhooks.py -k stripe"},
        "unique_files_touched": 23,
        "top_files_touched": [
            {"path": "src/webhooks/stripe.py", "count": 14},
            {"path": "tests/test_webhooks.py", "count": 11},
            {"path": ".env.test", "count": 6},
        ],
        "directory_concentration": 0.42,
        "tests_invoked": 12,
        "git_status_invoked": 4,
        "git_diff_invoked": 3,
        "pr_referenced": False,
        "assistant_chars": 28433,
        "user_chars": 4112,
        "reasoning_chars": 9218,
        "assistant_to_user_text_ratio": 6.91,
        "user_friction_signals": {"explicit_corrections": 3, "rephrased_retries": 2},
        "last_event_type": "message",
        "final_tool_status": "success",
        "error_concentration_tail": 0.7,
        "events_since_last_user_message": 12,
        "goal": "Add webhook signature verification + retry logic to acme-checkout's Stripe integration; ship behind a feature flag.",
        "topics": ["stripe-integration", "webhook-verification", "test-fixtures", "feature-flagging"],
        "external_systems_touched": ["github", "openai_api"],
        "verification_completeness": "lightly_verified",
        "prompt_quality_signal": "well_formed",
        "tasks": [
            {
                "task_id": "t1",
                "intent": "Add webhook signature verification using STRIPE_WEBHOOK_SECRET",
                "event_range": [0, 287],
                "task_type": "feature_implementation",
                "task_difficulty": {"scope": "few_files", "specification": "clear", "external_dependencies": "one", "verification_ease": "automated", "overall": "moderate"},
                "outcome": "completed",
                "outcome_evidence_event": 287,
                "time_to_first_verified_progress": 89,
            },
            {
                "task_id": "t2",
                "intent": "Add exponential-backoff retry on transient stripe errors",
                "event_range": [288, 562],
                "task_type": "feature_implementation",
                "task_difficulty": {"scope": "single_file", "specification": "clear", "external_dependencies": "one", "verification_ease": "automated", "overall": "moderate"},
                "outcome": "completed",
                "outcome_evidence_event": 562,
                "time_to_first_verified_progress": 354,
            },
            {
                "task_id": "t3",
                "intent": "Wire feature flag + write integration tests",
                "event_range": [563, 733],
                "task_type": "feature_implementation",
                "task_difficulty": {"scope": "few_files", "specification": "partial", "external_dependencies": "none", "verification_ease": "automated", "overall": "moderate"},
                "outcome": "partially_completed",
                "outcome_evidence_event": 733,
                "time_to_first_verified_progress": 612,
            },
        ],
        "friction_moments": [
            {
                "event_range": [42, 78],
                "task_id": "t1",
                "type": "tool_error_loop",
                "tool_category": "shell",
                "description": "pytest failed 7 times with KeyError: 'STRIPE_WEBHOOK_SECRET' — agent assumed conftest loaded .env.test, didn't.",
                "key_quote": "KeyError: 'STRIPE_WEBHOOK_SECRET'",
                "cost_events": 37,
                "cost_active_minutes": 8.3,
            },
            {
                "event_range": [612, 671],
                "task_id": "t3",
                "type": "verify_gap",
                "tool_category": "other",
                "description": "Marked task complete after agent ran tests once green; user noticed flag toggle wasn't actually wired in main flow.",
                "key_quote": "wait, did you actually plumb the flag through?",
                "cost_events": 60,
                "cost_active_minutes": 14.1,
            },
        ],
        "waste_signature": "tool_error_loop",
        "key_decisions": [
            {
                "event_index": 84,
                "decision": "Use stripe-python's official Webhook.construct_event helper rather than manual signature parsing",
                "retrospective": "Right call — signature verification is exactly the kind of thing you don't want to roll yourself.",
            },
            {
                "event_index": 412,
                "decision": "Exponential backoff with jitter capped at 60s for stripe retries",
                "retrospective": "Reasonable defaults; could revisit max_attempts later.",
            },
        ],
        "dead_ends": [
            {
                "event_range": [142, 198],
                "approach": "Mock the entire stripe SDK in unit tests",
                "abandoned_at": 198,
                "lesson": "stripe-mock fixtures from the SDK are simpler than rolling our own — saved time for the next webhook.",
            },
        ],
        "recurring_environmental_issues": [
            {
                "description": "STRIPE_WEBHOOK_SECRET missing in test env — pytest conftest doesn't auto-load .env.test. Add `python-dotenv` autoload or `pytest-env` to pyproject.",
                "occurrences": [42, 67, 89, 142, 198, 224, 287],
            },
        ],
        "user_caught_model_errors": {
            "count": 2,
            "examples": [
                {"event_index": 612, "what_user_caught": "Agent claimed feature flag was wired in main flow but only added it to webhook handler module"},
                {"event_index": 156, "what_user_caught": "Agent suggested storing webhook secret in code; user redirected to env var"},
            ],
        },
        "counterfactual": "If conftest.py had loaded .env.test at session start (event 0), the entire 37-event KeyError loop at events 42-78 would have evaporated — that's 8+ minutes saved on the very first try.",
        "lesson_for_agent": "When tests fail with KeyError on an env var, check conftest/dotenv loading before assuming the var is missing from the env file.",
        "lesson_for_user": "Add `pytest-env` to pyproject.toml dev deps with `[tool.pytest_env] STRIPE_WEBHOOK_SECRET = whsec_test_dummy` — eliminates this class of error in every webhook-related session.",
        "notable": "The user-caught error at event 612 (incomplete flag plumbing) is a verify_gap that would have shipped to staging if not caught. Worth flagging.",
        "narrative_quality": "high",
    },
    {
        "session_id": "claude:7c2d8e34-f4a5-4b67-89cd-ef1234567802",
        "agent": "claude",
        "project_path": "/Users/alex/work/acme-checkout",
        "project_label": "work/acme-checkout",
        "git_branch_last": "feat/checkout-flow-e2e",
        "models_used": ["claude-opus-4-7"],
        "primary_model": "claude-opus-4-7",
        "started_at": "2026-04-23T14:02:08Z",
        "ended_at": "2026-04-23T17:31:40Z",
        "wall_clock_minutes": 209.5,
        "active_minutes": 162.4,
        "primary_burst_minutes": 89.2,
        "longest_idle_minutes": 8.4,
        "bursts": 2,
        "events_per_active_minute": 7.9,
        "time_of_day_buckets": {"morning": 0, "afternoon": 1284, "evening": 0, "night": 0},
        "weekday": "Thursday",
        "event_count": 1284,
        "tool_call_count": 472,
        "user_turn_count": 28,
        "subagent_count": 0,
        "subagent_event_count": 0,
        "subagent_types_spawned": {},
        "tool_call_distribution": {"mcp__chrome-devtools__navigate": 38, "mcp__chrome-devtools__take_screenshot": 34, "mcp__chrome-devtools__click": 29, "Bash": 88, "Read": 51},
        "tool_category_distribution": {"browser": 142, "shell": 88, "read": 76, "write": 41, "other": 125},
        "tool_error_rate": 0.097,
        "tool_error_classes": {"tool_error": 41, "approval_required": 5},
        "most_repeated_tool_call": {"tool": "mcp__chrome-devtools__take_screenshot", "input_hash": "f4e3d2c1b0", "count": 22, "input_preview": "{}"},
        "unique_files_touched": 31,
        "top_files_touched": [
            {"path": "tests/e2e/checkout.spec.ts", "count": 18},
            {"path": "playwright.config.ts", "count": 9},
        ],
        "directory_concentration": 0.55,
        "tests_invoked": 22,
        "git_status_invoked": 3,
        "git_diff_invoked": 2,
        "pr_referenced": False,
        "assistant_chars": 51204,
        "user_chars": 6817,
        "reasoning_chars": 18421,
        "assistant_to_user_text_ratio": 7.51,
        "user_friction_signals": {"explicit_corrections": 6, "rephrased_retries": 4},
        "last_event_type": "message",
        "final_tool_status": "error",
        "error_concentration_tail": 1.4,
        "events_since_last_user_message": 22,
        "goal": "Get the checkout-flow Playwright e2e test passing reliably across local + CI.",
        "topics": ["playwright-e2e", "browser-automation", "stripe-test-mode", "ci-flake"],
        "external_systems_touched": ["github", "browser"],
        "verification_completeness": "claimed_only",
        "prompt_quality_signal": "well_formed",
        "tasks": [
            {
                "task_id": "t1",
                "intent": "Diagnose why checkout.spec.ts is flaky on the CI runner",
                "event_range": [0, 612],
                "task_type": "debugging",
                "task_difficulty": {"scope": "cross_module", "specification": "exploratory", "external_dependencies": "multiple", "verification_ease": "partial", "overall": "hard"},
                "outcome": "stuck_at_end",
                "outcome_evidence_event": 612,
                "time_to_first_verified_progress": -1,
            },
            {
                "task_id": "t2",
                "intent": "Switch to Stripe test-mode webhook fixtures instead of live API",
                "event_range": [613, 1283],
                "task_type": "infrastructure",
                "task_difficulty": {"scope": "few_files", "specification": "clear", "external_dependencies": "one", "verification_ease": "automated", "overall": "moderate"},
                "outcome": "partially_completed",
                "outcome_evidence_event": 1283,
                "time_to_first_verified_progress": 891,
            },
        ],
        "friction_moments": [
            {
                "event_range": [78, 142],
                "task_id": "t1",
                "type": "browser_spiral",
                "tool_category": "browser",
                "description": "8 navigate→screenshot→click cycles trying to reproduce checkout flow; agent never noticed the test was hitting the production Stripe key by mistake.",
                "key_quote": "the page just keeps redirecting to /checkout-success even though I haven't filled the card?",
                "cost_events": 65,
                "cost_active_minutes": 16.7,
            },
            {
                "event_range": [342, 478],
                "task_id": "t1",
                "type": "tool_error_loop",
                "tool_category": "browser",
                "description": "Playwright timing out on .stripe-iframe; agent retried with longer timeouts 4 times instead of switching to a frame-aware selector.",
                "key_quote": "TimeoutError: page.click: Timeout 30000ms exceeded.",
                "cost_events": 137,
                "cost_active_minutes": 28.4,
            },
            {
                "event_range": [903, 1184],
                "task_id": "t2",
                "type": "exploration_drift",
                "tool_category": "other",
                "description": "Investigated 4 different test-mode webhook setup approaches before user shared the existing stripe-mock fixture from the unit tests.",
                "key_quote": "we already have stripe-mock set up in the unit tests, just import that?",
                "cost_events": 282,
                "cost_active_minutes": 51.8,
            },
        ],
        "waste_signature": "exploration_drift",
        "key_decisions": [
            {
                "event_index": 624,
                "decision": "Pivot from debugging the flake to switching the test entirely to test-mode fixtures",
                "retrospective": "Reasonable pivot — was clearly stuck; but should have checked existing fixtures (event 1184 showed they already existed) before researching new ones.",
            },
        ],
        "dead_ends": [
            {
                "event_range": [342, 478],
                "approach": "Increase Playwright timeout from 30s → 60s → 120s",
                "abandoned_at": 478,
                "lesson": "When timeout grows past 30s, the bug isn't speed — switch to frame-aware locators (locator.frameLocator) or check for navigation events.",
            },
            {
                "event_range": [903, 1100],
                "approach": "Set up @stripe-mock/server as new test infrastructure",
                "abandoned_at": 1184,
                "lesson": "Always grep for existing test fixtures before designing new ones — `grep -r stripe-mock tests/` would have saved an hour.",
            },
        ],
        "recurring_environmental_issues": [
            {
                "description": "Playwright's chromium browser dies between test files when test isolation is set to 'process'. Fix: set fullyParallel: false in playwright.config.ts for the e2e suite.",
                "occurrences": [156, 287, 412, 698],
            },
        ],
        "user_caught_model_errors": {
            "count": 3,
            "examples": [
                {"event_index": 1184, "what_user_caught": "Agent investigating new test fixture approaches when stripe-mock was already configured for unit tests"},
                {"event_index": 124, "what_user_caught": "Agent didn't notice the test was using the live Stripe key, not the test key"},
                {"event_index": 412, "what_user_caught": "Agent kept extending Playwright timeouts instead of fixing the underlying frame issue"},
            ],
        },
        "counterfactual": "At event 78, if the agent had checked the .env.test STRIPE keys (one Read call) before launching browser sessions, it would have caught the live-key issue immediately and avoided 65 events of confused browser_spiral.",
        "lesson_for_agent": "Before doing browser automation against an external service, verify which API keys / test mode flags are loaded — it's a 1-event check that prevents 30+ event spirals.",
        "lesson_for_user": "Add a fail-fast assertion at top of playwright.config.ts: `if (process.env.STRIPE_KEY?.startsWith('sk_live')) throw new Error('production stripe key in test config')`.",
        "notable": "Three different friction moments traceable to the same root cause: insufficient pre-flight checks of test environment state. Pattern across this project.",
        "narrative_quality": "high",
    },
    {
        "session_id": "claude:6e1f7a9b-c2d3-4e45-67ab-123456789803",
        "agent": "claude",
        "project_path": "/Users/alex/work/acme-checkout",
        "project_label": "work/acme-checkout",
        "git_branch_last": "main",
        "models_used": ["claude-sonnet-4-6"],
        "primary_model": "claude-sonnet-4-6",
        "started_at": "2026-04-24T10:30:00Z",
        "ended_at": "2026-04-24T11:45:22Z",
        "wall_clock_minutes": 75.4,
        "active_minutes": 64.2,
        "primary_burst_minutes": 64.2,
        "longest_idle_minutes": 1.2,
        "bursts": 1,
        "events_per_active_minute": 9.1,
        "time_of_day_buckets": {"morning": 584, "afternoon": 0, "evening": 0, "night": 0},
        "weekday": "Friday",
        "event_count": 584,
        "tool_call_count": 218,
        "user_turn_count": 14,
        "subagent_count": 4,
        "subagent_event_count": 287,
        "subagent_types_spawned": {"explore": 3, "general-purpose": 1},
        "tool_call_distribution": {"Task": 4, "Read": 89, "Bash": 47, "Grep": 38, "Edit": 12},
        "tool_category_distribution": {"delegation": 4, "read": 134, "shell": 47, "write": 12, "other": 21},
        "tool_error_rate": 0.027,
        "tool_error_classes": {"tool_error": 6},
        "most_repeated_tool_call": {"tool": "Read", "input_hash": "98abcdef12", "count": 4, "input_preview": "{\"file_path\": \"src/payments/processor.py\"}"},
        "unique_files_touched": 47,
        "top_files_touched": [
            {"path": "src/payments/processor.py", "count": 12},
            {"path": "src/payments/types.py", "count": 8},
        ],
        "directory_concentration": 0.71,
        "tests_invoked": 0,
        "git_status_invoked": 1,
        "git_diff_invoked": 6,
        "pr_referenced": True,
        "assistant_chars": 31420,
        "user_chars": 3214,
        "reasoning_chars": 11003,
        "assistant_to_user_text_ratio": 9.78,
        "user_friction_signals": {"explicit_corrections": 1, "rephrased_retries": 0},
        "last_event_type": "message",
        "final_tool_status": "success",
        "error_concentration_tail": 0.0,
        "events_since_last_user_message": 4,
        "goal": "Review PR #421 (refund endpoint) — code review + suggest improvements before approval.",
        "topics": ["code-review", "pr-feedback", "refund-flow", "payments"],
        "external_systems_touched": ["github"],
        "verification_completeness": "thoroughly_verified",
        "prompt_quality_signal": "well_formed",
        "tasks": [
            {
                "task_id": "t1",
                "intent": "Diff PR #421 against main, summarize scope",
                "event_range": [0, 89],
                "task_type": "code_review",
                "task_difficulty": {"scope": "few_files", "specification": "clear", "external_dependencies": "one", "verification_ease": "partial", "overall": "moderate"},
                "outcome": "completed",
                "outcome_evidence_event": 89,
                "time_to_first_verified_progress": 34,
            },
            {
                "task_id": "t2",
                "intent": "Spawn parallel subagents to deep-review error handling, type safety, and test coverage",
                "event_range": [90, 462],
                "task_type": "code_review",
                "task_difficulty": {"scope": "cross_module", "specification": "clear", "external_dependencies": "none", "verification_ease": "partial", "overall": "moderate"},
                "outcome": "completed",
                "outcome_evidence_event": 462,
                "time_to_first_verified_progress": 287,
            },
            {
                "task_id": "t3",
                "intent": "Synthesize subagent findings, post 6 review comments on the PR",
                "event_range": [463, 583],
                "task_type": "code_review",
                "task_difficulty": {"scope": "single_file", "specification": "clear", "external_dependencies": "one", "verification_ease": "automated", "overall": "trivial"},
                "outcome": "completed",
                "outcome_evidence_event": 583,
                "time_to_first_verified_progress": 521,
            },
        ],
        "friction_moments": [
            {
                "event_range": [12, 34],
                "task_id": "t1",
                "type": "blind_retry",
                "tool_category": "shell",
                "description": "Diffed against local main without git fetch; saw 47 changed files when PR actually had 9. Retried after user intervention.",
                "key_quote": "47 files? did you fetch first?",
                "cost_events": 23,
                "cost_active_minutes": 4.1,
            },
        ],
        "waste_signature": "blind_retry",
        "key_decisions": [
            {
                "event_index": 92,
                "decision": "Spawn 3 parallel subagents (error handling / types / tests) rather than reviewing serially",
                "retrospective": "Good call — saved ~25 minutes vs serial review on this 9-file PR.",
            },
        ],
        "dead_ends": [],
        "recurring_environmental_issues": [],
        "user_caught_model_errors": {
            "count": 1,
            "examples": [
                {"event_index": 28, "what_user_caught": "Agent diffed against stale local main (47 files) without fetching first"},
            ],
        },
        "counterfactual": "If the array-pr-review skill had `git fetch origin main` as step 0, the 23-event blind_retry at events 12-34 would not have happened.",
        "lesson_for_agent": "Always `git fetch origin main` before diffing for PR review. Single command, prevents stale-main diff inflation.",
        "lesson_for_user": "Edit your code-review skill prompt to start with: 'Step 1: git fetch origin main && git diff origin/main...HEAD'.",
        "notable": "Despite the early friction, this was the most productive session of the week — 6 actionable review comments on a refund flow PR in 75 minutes.",
        "narrative_quality": "high",
    },
    {
        "session_id": "codex:019f8b21-3c45-7d89-ab12-cdef34567804",
        "agent": "codex",
        "project_path": "/Users/alex/work/acme-api",
        "project_label": "work/acme-api",
        "git_branch_last": "feat/refund-endpoint",
        "models_used": ["gpt-5.4"],
        "primary_model": "gpt-5.4",
        "started_at": "2026-04-21T16:42:00Z",
        "ended_at": "2026-04-21T18:18:14Z",
        "wall_clock_minutes": 96.2,
        "active_minutes": 78.4,
        "primary_burst_minutes": 78.4,
        "longest_idle_minutes": 2.1,
        "bursts": 1,
        "events_per_active_minute": 6.2,
        "time_of_day_buckets": {"morning": 0, "afternoon": 488, "evening": 0, "night": 0},
        "weekday": "Tuesday",
        "event_count": 488,
        "tool_call_count": 162,
        "user_turn_count": 11,
        "subagent_count": 0,
        "subagent_event_count": 0,
        "subagent_types_spawned": {},
        "tool_call_distribution": {"exec_command": 79, "apply_patch": 41, "view_image": 0, "read_stdin": 24, "write_stdin": 18},
        "tool_category_distribution": {"shell": 79, "write": 41, "other": 42},
        "tool_error_rate": 0.123,
        "tool_error_classes": {"nonzero_exit": 14, "permission_denied": 3, "approval_required": 3},
        "most_repeated_tool_call": {"tool": "exec_command", "input_hash": "abc1234567", "count": 6, "input_preview": "{\"command\": \"alembic upgrade head\"}"},
        "unique_files_touched": 14,
        "top_files_touched": [
            {"path": "src/api/refunds.py", "count": 19},
            {"path": "alembic/versions/0042_refunds.py", "count": 14},
            {"path": "tests/test_refunds.py", "count": 11},
        ],
        "directory_concentration": 0.58,
        "tests_invoked": 9,
        "git_status_invoked": 2,
        "git_diff_invoked": 3,
        "pr_referenced": False,
        "assistant_chars": 19432,
        "user_chars": 2417,
        "reasoning_chars": 7891,
        "assistant_to_user_text_ratio": 8.04,
        "user_friction_signals": {"explicit_corrections": 2, "rephrased_retries": 1},
        "last_event_type": "tool_result",
        "final_tool_status": "success",
        "error_concentration_tail": 0.4,
        "events_since_last_user_message": 18,
        "goal": "Add POST /refunds endpoint to acme-api with proper Stripe integration + alembic migration.",
        "topics": ["fastapi", "alembic-migration", "refund-endpoint", "stripe-sdk"],
        "external_systems_touched": ["github", "openai_api"],
        "verification_completeness": "lightly_verified",
        "prompt_quality_signal": "underspecified",
        "tasks": [
            {
                "task_id": "t1",
                "intent": "Add Refund SQLAlchemy model + alembic migration",
                "event_range": [0, 218],
                "task_type": "feature_implementation",
                "task_difficulty": {"scope": "few_files", "specification": "partial", "external_dependencies": "one", "verification_ease": "partial", "overall": "moderate"},
                "outcome": "completed",
                "outcome_evidence_event": 218,
                "time_to_first_verified_progress": 184,
            },
            {
                "task_id": "t2",
                "intent": "Implement POST /refunds with Stripe.Refund.create",
                "event_range": [219, 487],
                "task_type": "feature_implementation",
                "task_difficulty": {"scope": "single_file", "specification": "clear", "external_dependencies": "one", "verification_ease": "automated", "overall": "moderate"},
                "outcome": "completed",
                "outcome_evidence_event": 487,
                "time_to_first_verified_progress": 387,
            },
        ],
        "friction_moments": [
            {
                "event_range": [124, 178],
                "task_id": "t1",
                "type": "verify_gap",
                "tool_category": "shell",
                "description": "Migration created but not tested with rollback. User asked 'can we roll this back?' — agent had to add downgrade() block after the fact.",
                "key_quote": "what about the downgrade?",
                "cost_events": 55,
                "cost_active_minutes": 11.2,
            },
            {
                "event_range": [304, 387],
                "task_id": "t2",
                "type": "exploration_drift",
                "tool_category": "shell",
                "description": "Agent re-implemented stripe error handling from scratch instead of importing the project's existing StripeRetry decorator from src/payments/.",
                "key_quote": "we have a StripeRetry decorator already",
                "cost_events": 84,
                "cost_active_minutes": 18.7,
            },
        ],
        "waste_signature": "exploration_drift",
        "key_decisions": [
            {
                "event_index": 88,
                "decision": "Use alembic autogenerate for the migration rather than handwriting it",
                "retrospective": "Good — schema was simple enough that autogenerate was correct first try.",
            },
        ],
        "dead_ends": [
            {
                "event_range": [304, 387],
                "approach": "Hand-roll exponential-backoff retry decorator inline in refunds.py",
                "abandoned_at": 387,
                "lesson": "Always grep for existing decorators (`grep -r '^def.*retry' src/payments/`) before writing new retry logic.",
            },
        ],
        "recurring_environmental_issues": [
            {
                "description": "alembic upgrade head fails on first try with 'database is locked' when dev server is running. Fix: stop dev server before migrations OR use SQLite WAL mode in dev.",
                "occurrences": [142, 167, 193, 214, 256],
            },
        ],
        "user_caught_model_errors": {
            "count": 2,
            "examples": [
                {"event_index": 124, "what_user_caught": "Migration had no downgrade() — agent assumed it wasn't needed for forward-only deploy"},
                {"event_index": 304, "what_user_caught": "Agent reimplemented retry logic when StripeRetry already existed in src/payments/"},
            ],
        },
        "counterfactual": "If the prompt had said 'use existing StripeRetry decorator from src/payments/' (one sentence at the start), the 84-event reimplementation drift at events 304-387 would not have happened.",
        "lesson_for_agent": "When implementing error handling for an external service, grep for existing utilities (`*Retry`, `*Backoff`, `with_retry`) before writing inline.",
        "lesson_for_user": "Add to acme-api's CLAUDE.md: 'Stripe error handling: use src/payments/decorators.StripeRetry. Don't roll your own.'",
        "notable": "First Codex session of the week — apply_patch worked smoothly on this codebase but the project has no AGENTS.md so Codex had less context than Claude on the same project.",
        "narrative_quality": "high",
    },
    {
        "session_id": "claude:5d3e8c4f-1a2b-4c56-78de-fabc12345805",
        "agent": "claude",
        "project_path": "/Users/alex/work/acme-mobile",
        "project_label": "work/acme-mobile",
        "git_branch_last": "fix/expo-sdk-upgrade",
        "models_used": ["claude-sonnet-4-6"],
        "primary_model": "claude-sonnet-4-6",
        "started_at": "2026-04-25T22:14:00Z",
        "ended_at": "2026-04-26T01:42:18Z",
        "wall_clock_minutes": 208.3,
        "active_minutes": 134.8,
        "primary_burst_minutes": 92.4,
        "longest_idle_minutes": 18.7,
        "bursts": 3,
        "events_per_active_minute": 8.7,
        "time_of_day_buckets": {"morning": 0, "afternoon": 0, "evening": 412, "night": 762},
        "weekday": "Saturday",
        "event_count": 1174,
        "tool_call_count": 421,
        "user_turn_count": 17,
        "subagent_count": 1,
        "subagent_event_count": 87,
        "subagent_types_spawned": {"explore": 1},
        "tool_call_distribution": {"Bash": 184, "Edit": 67, "Read": 92, "Grep": 31, "Glob": 12},
        "tool_category_distribution": {"shell": 184, "write": 67, "read": 135, "delegation": 8, "other": 27},
        "tool_error_rate": 0.182,
        "tool_error_classes": {"tool_error": 67, "permission_denied": 4, "nonzero_exit": 6},
        "most_repeated_tool_call": {"tool": "Bash", "input_hash": "deadbeefcc", "count": 14, "input_preview": "{\"command\": \"npx expo install --fix\"}"},
        "unique_files_touched": 38,
        "top_files_touched": [
            {"path": "package.json", "count": 23},
            {"path": "ios/Podfile", "count": 12},
            {"path": "metro.config.js", "count": 8},
        ],
        "directory_concentration": 0.41,
        "tests_invoked": 3,
        "git_status_invoked": 8,
        "git_diff_invoked": 5,
        "pr_referenced": False,
        "assistant_chars": 47218,
        "user_chars": 4912,
        "reasoning_chars": 16204,
        "assistant_to_user_text_ratio": 9.61,
        "user_friction_signals": {"explicit_corrections": 5, "rephrased_retries": 3},
        "last_event_type": "message",
        "final_tool_status": "error",
        "error_concentration_tail": 1.8,
        "events_since_last_user_message": 41,
        "goal": "Upgrade acme-mobile from Expo SDK 50 → 53; resolve all peer-dep warnings; ship a working build.",
        "topics": ["expo-sdk-upgrade", "react-native", "peer-dependencies", "ios-pods"],
        "external_systems_touched": ["github"],
        "verification_completeness": "lightly_verified",
        "prompt_quality_signal": "well_formed",
        "tasks": [
            {
                "task_id": "t1",
                "intent": "Bump Expo SDK + run npx expo install --fix; resolve peer-dep warnings",
                "event_range": [0, 521],
                "task_type": "infrastructure",
                "task_difficulty": {"scope": "system_wide", "specification": "exploratory", "external_dependencies": "multiple", "verification_ease": "requires_human", "overall": "very_hard"},
                "outcome": "stuck_at_end",
                "outcome_evidence_event": 521,
                "time_to_first_verified_progress": -1,
            },
            {
                "task_id": "t2",
                "intent": "Resolve iOS Podfile.lock conflicts after RN core upgrade",
                "event_range": [522, 1173],
                "task_type": "debugging",
                "task_difficulty": {"scope": "few_files", "specification": "exploratory", "external_dependencies": "multiple", "verification_ease": "requires_human", "overall": "hard"},
                "outcome": "partially_completed",
                "outcome_evidence_event": 1173,
                "time_to_first_verified_progress": 891,
            },
        ],
        "friction_moments": [
            {
                "event_range": [78, 287],
                "task_id": "t1",
                "type": "blind_retry",
                "tool_category": "shell",
                "description": "Ran `npx expo install --fix` 14 times across 4 hours hoping the peer-dep warnings would self-resolve; they don't.",
                "key_quote": "still 18 warnings — try again with --force?",
                "cost_events": 210,
                "cost_active_minutes": 47.3,
            },
            {
                "event_range": [612, 814],
                "task_id": "t2",
                "type": "tool_error_loop",
                "tool_category": "shell",
                "description": "Pod install failed 8 times with conflicting Folly versions; agent kept clearing caches instead of pinning the version.",
                "key_quote": "[!] Unable to find a specification for `Folly`",
                "cost_events": 203,
                "cost_active_minutes": 38.4,
            },
            {
                "event_range": [987, 1100],
                "task_id": "t2",
                "type": "context_loss",
                "tool_category": "shell",
                "description": "Re-read package.json + Podfile that had been modified 8 events earlier; lost track of which lockfile was already regenerated.",
                "key_quote": "wait, did I already run pod install in this session?",
                "cost_events": 114,
                "cost_active_minutes": 22.1,
            },
        ],
        "waste_signature": "blind_retry",
        "key_decisions": [
            {
                "event_index": 542,
                "decision": "Stop --force-installing and instead read the EXPO sdk-53 upgrade guide first",
                "retrospective": "Right move 4 hours late — should have been step 1.",
            },
        ],
        "dead_ends": [
            {
                "event_range": [78, 287],
                "approach": "Repeatedly run `npx expo install --fix` hoping it'll converge",
                "abandoned_at": 287,
                "lesson": "When auto-install can't resolve peer deps after 2-3 attempts, manually pin the conflicting deps in package.json — don't loop.",
            },
        ],
        "recurring_environmental_issues": [
            {
                "description": "iOS Podfile resolution flakes after major RN upgrades. Workaround: rm -rf ios/Pods ios/Podfile.lock && pod install with --repo-update.",
                "occurrences": [612, 678, 745, 814, 892],
            },
        ],
        "user_caught_model_errors": {
            "count": 1,
            "examples": [
                {"event_index": 542, "what_user_caught": "Agent looping on --force flag instead of reading the SDK 53 release notes"},
            ],
        },
        "counterfactual": "At event 78, reading the official Expo SDK 53 upgrade guide first (one Read of expo.dev/changelog/sdk-53) would have surfaced the 4 known breaking changes and prevented 47 minutes of blind retries.",
        "lesson_for_agent": "For framework version upgrades, read the official changelog/migration guide BEFORE running upgrade commands. 'expo install --fix' loops are almost always missing-context bugs.",
        "lesson_for_user": "Late-night SDK upgrade sessions correlate with blind retries — try framework upgrades during morning hours when the cost of pausing to read docs is lower.",
        "notable": "Session ran 8pm Saturday → 1:30am — by far the latest session of the month, and produced the most blind_retry friction. Pattern: time-of-day correlates with retry-loop behavior.",
        "narrative_quality": "high",
    },
    {
        "session_id": "gemini:a4b9c3d2-e1f0-4567-89ab-cdef98765806",
        "agent": "gemini",
        "project_path": "/Users/alex/work/acme-tooling",
        "project_label": "work/acme-tooling",
        "git_branch_last": "main",
        "models_used": ["gemini-3-pro-preview"],
        "primary_model": "gemini-3-pro-preview",
        "started_at": "2026-04-21T08:24:00Z",
        "ended_at": "2026-04-21T08:51:38Z",
        "wall_clock_minutes": 27.6,
        "active_minutes": 24.1,
        "primary_burst_minutes": 24.1,
        "longest_idle_minutes": 0.8,
        "bursts": 1,
        "events_per_active_minute": 6.5,
        "time_of_day_buckets": {"morning": 156, "afternoon": 0, "evening": 0, "night": 0},
        "weekday": "Tuesday",
        "event_count": 156,
        "tool_call_count": 52,
        "user_turn_count": 6,
        "subagent_count": 0,
        "subagent_event_count": 0,
        "subagent_types_spawned": {},
        "tool_call_distribution": {"run_shell_command": 24, "read_file": 14, "list_directory": 6, "write_file": 8},
        "tool_category_distribution": {"shell": 24, "read": 20, "write": 8},
        "tool_error_rate": 0.038,
        "tool_error_classes": {"tool_error": 2},
        "most_repeated_tool_call": {"tool": "run_shell_command", "input_hash": "fedcba9876", "count": 3, "input_preview": "{\"command\": \"python scripts/cleanup_old_logs.py --dry-run\"}"},
        "unique_files_touched": 4,
        "top_files_touched": [
            {"path": "scripts/cleanup_old_logs.py", "count": 8},
        ],
        "directory_concentration": 0.92,
        "tests_invoked": 0,
        "git_status_invoked": 1,
        "git_diff_invoked": 1,
        "pr_referenced": False,
        "assistant_chars": 8214,
        "user_chars": 1342,
        "reasoning_chars": 2104,
        "assistant_to_user_text_ratio": 6.12,
        "user_friction_signals": {"explicit_corrections": 0, "rephrased_retries": 0},
        "last_event_type": "message",
        "final_tool_status": "success",
        "error_concentration_tail": 0.0,
        "events_since_last_user_message": 6,
        "goal": "Write a one-off Python script to clean up production log files older than 30 days from S3.",
        "topics": ["python-scripting", "s3-cleanup", "log-rotation", "ops-task"],
        "external_systems_touched": ["aws"],
        "verification_completeness": "thoroughly_verified",
        "prompt_quality_signal": "well_formed",
        "tasks": [
            {
                "task_id": "t1",
                "intent": "Implement scripts/cleanup_old_logs.py with --dry-run + --apply modes; verify against staging logs first",
                "event_range": [0, 155],
                "task_type": "infrastructure",
                "task_difficulty": {"scope": "single_file", "specification": "clear", "external_dependencies": "one", "verification_ease": "partial", "overall": "trivial"},
                "outcome": "completed",
                "outcome_evidence_event": 155,
                "time_to_first_verified_progress": 67,
            },
        ],
        "friction_moments": [],
        "waste_signature": "none",
        "key_decisions": [
            {
                "event_index": 34,
                "decision": "Use boto3.paginator for S3 listing rather than list_objects_v2 directly",
                "retrospective": "Right call — staging bucket has 50K+ objects.",
            },
        ],
        "dead_ends": [],
        "recurring_environmental_issues": [],
        "user_caught_model_errors": {"count": 0, "examples": []},
        "counterfactual": "No meaningful counterfactual — this was a clean session with appropriate dry-run verification before --apply.",
        "lesson_for_agent": "When asked for a one-off cleanup script touching production data, default to --dry-run-first and ask for explicit --apply confirmation. This session did that correctly.",
        "lesson_for_user": "",
        "notable": "Cleanest session of the week — clear goal, single file, dry-run before apply, no friction. Worth noting what made it work: explicit constraints in the initial prompt.",
        "narrative_quality": "high",
    },
    {
        "session_id": "claude:9c8d7e6f-5a4b-3c12-de56-789012345807",
        "agent": "claude",
        "project_path": "/Users/alex/work/acme-api",
        "project_label": "work/acme-api",
        "git_branch_last": "feat/usage-metering",
        "models_used": ["claude-sonnet-4-6"],
        "primary_model": "claude-sonnet-4-6",
        "started_at": "2026-04-20T11:00:00Z",
        "ended_at": "2026-04-20T13:24:11Z",
        "wall_clock_minutes": 144.2,
        "active_minutes": 121.4,
        "primary_burst_minutes": 121.4,
        "longest_idle_minutes": 1.4,
        "bursts": 1,
        "events_per_active_minute": 7.6,
        "time_of_day_buckets": {"morning": 567, "afternoon": 354, "evening": 0, "night": 0},
        "weekday": "Monday",
        "event_count": 921,
        "tool_call_count": 312,
        "user_turn_count": 22,
        "subagent_count": 6,
        "subagent_event_count": 487,
        "subagent_types_spawned": {"explore": 4, "general-purpose": 2},
        "tool_call_distribution": {"Task": 6, "Read": 92, "Edit": 47, "Bash": 71, "Grep": 38},
        "tool_category_distribution": {"delegation": 6, "read": 130, "write": 47, "shell": 71, "other": 58},
        "tool_error_rate": 0.045,
        "tool_error_classes": {"tool_error": 14},
        "most_repeated_tool_call": {"tool": "Task", "input_hash": "012345abcd", "count": 6, "input_preview": "{\"description\": \"explore usage tracking patterns\"}"},
        "unique_files_touched": 52,
        "top_files_touched": [
            {"path": "src/api/usage.py", "count": 18},
            {"path": "src/api/middleware.py", "count": 11},
        ],
        "directory_concentration": 0.48,
        "tests_invoked": 8,
        "git_status_invoked": 3,
        "git_diff_invoked": 4,
        "pr_referenced": False,
        "assistant_chars": 38421,
        "user_chars": 5104,
        "reasoning_chars": 14218,
        "assistant_to_user_text_ratio": 7.53,
        "user_friction_signals": {"explicit_corrections": 4, "rephrased_retries": 2},
        "last_event_type": "message",
        "final_tool_status": "success",
        "error_concentration_tail": 0.5,
        "events_since_last_user_message": 18,
        "goal": "Add per-tenant usage metering middleware to acme-api with persistent daily aggregates.",
        "topics": ["usage-metering", "middleware", "subagent-delegation", "redis-aggregates"],
        "external_systems_touched": ["github"],
        "verification_completeness": "lightly_verified",
        "prompt_quality_signal": "underspecified",
        "tasks": [
            {
                "task_id": "t1",
                "intent": "Research existing usage tracking in codebase via 4 parallel exploration subagents",
                "event_range": [0, 287],
                "task_type": "exploration",
                "task_difficulty": {"scope": "system_wide", "specification": "exploratory", "external_dependencies": "none", "verification_ease": "requires_human", "overall": "moderate"},
                "outcome": "completed",
                "outcome_evidence_event": 287,
                "time_to_first_verified_progress": 234,
            },
            {
                "task_id": "t2",
                "intent": "Implement usage middleware + redis aggregates",
                "event_range": [288, 920],
                "task_type": "feature_implementation",
                "task_difficulty": {"scope": "cross_module", "specification": "partial", "external_dependencies": "one", "verification_ease": "automated", "overall": "hard"},
                "outcome": "completed",
                "outcome_evidence_event": 920,
                "time_to_first_verified_progress": 612,
            },
        ],
        "friction_moments": [
            {
                "event_range": [12, 156],
                "task_id": "t1",
                "type": "over_delegation",
                "tool_category": "delegation",
                "description": "Spawned 4 subagents to 'explore usage tracking' on a small codebase where one Read of middleware.py would have answered the question. 487 wasted subagent events.",
                "key_quote": "explore the codebase and find any existing usage tracking patterns",
                "cost_events": 145,
                "cost_active_minutes": 24.7,
            },
            {
                "event_range": [387, 487],
                "task_id": "t2",
                "type": "context_loss",
                "tool_category": "other",
                "description": "After subagent results, agent re-read middleware.py twice — context from subagent summaries was incomplete; lost the existing RateLimiter pattern.",
                "key_quote": "let me re-check the middleware structure",
                "cost_events": 101,
                "cost_active_minutes": 18.2,
            },
        ],
        "waste_signature": "over_delegation",
        "key_decisions": [
            {
                "event_index": 612,
                "decision": "Use Redis HINCRBY for atomic per-tenant counters rather than in-memory + flush",
                "retrospective": "Right call — multi-process worker setup means in-memory wouldn't work.",
            },
        ],
        "dead_ends": [
            {
                "event_range": [12, 156],
                "approach": "Spawn 4 parallel exploration subagents on a small codebase",
                "abandoned_at": 287,
                "lesson": "Subagents make sense for >50-file codebases or genuinely-parallel research. For <20 file projects, direct Read/Grep is faster and preserves context.",
            },
        ],
        "recurring_environmental_issues": [],
        "user_caught_model_errors": {
            "count": 2,
            "examples": [
                {"event_index": 156, "what_user_caught": "4 subagents for a 19-file middleware folder is overkill"},
                {"event_index": 487, "what_user_caught": "Existing RateLimiter middleware pattern was missed despite 4 exploration subagents"},
            ],
        },
        "counterfactual": "If the agent had Read middleware.py + Grep'd for 'usage|track' first (3 events), instead of spawning 4 subagents (145 events), it would have found the existing RateLimiter pattern in under 30 seconds.",
        "lesson_for_agent": "Default to direct Read+Grep on codebases <50 files. Subagents are for parallelism on broad questions, not 'I'm not sure where to look'.",
        "lesson_for_user": "Add to acme-api/CLAUDE.md: 'middleware patterns: src/api/middleware.py — use the existing RateLimiter base class for new throttling middleware.'",
        "notable": "The 4-subagent fan-out felt productive (lots of events, lots of output) but produced strictly less context than 3 direct reads would have. Classic over_delegation pattern.",
        "narrative_quality": "high",
    },
    {
        "session_id": "claude:1a2b3c4d-5e6f-7890-abcd-ef0123456808",
        "agent": "claude",
        "project_path": "/Users/alex/work/acme-checkout",
        "project_label": "work/acme-checkout",
        "git_branch_last": "feat/coupon-codes",
        "models_used": ["claude-sonnet-4-6"],
        "primary_model": "claude-sonnet-4-6",
        "started_at": "2026-04-19T15:32:00Z",
        "ended_at": "2026-04-19T16:48:42Z",
        "wall_clock_minutes": 76.7,
        "active_minutes": 71.2,
        "primary_burst_minutes": 71.2,
        "longest_idle_minutes": 0.9,
        "bursts": 1,
        "events_per_active_minute": 8.0,
        "time_of_day_buckets": {"morning": 0, "afternoon": 568, "evening": 0, "night": 0},
        "weekday": "Sunday",
        "event_count": 568,
        "tool_call_count": 192,
        "user_turn_count": 16,
        "subagent_count": 0,
        "subagent_event_count": 0,
        "subagent_types_spawned": {},
        "tool_call_distribution": {"Read": 47, "Edit": 38, "Bash": 41, "Grep": 28, "Glob": 14},
        "tool_category_distribution": {"read": 89, "write": 38, "shell": 41, "other": 24},
        "tool_error_rate": 0.052,
        "tool_error_classes": {"tool_error": 10},
        "most_repeated_tool_call": {"tool": "Edit", "input_hash": "98ab76cd54", "count": 7, "input_preview": "src/checkout/coupons.py"},
        "unique_files_touched": 18,
        "top_files_touched": [
            {"path": "src/checkout/coupons.py", "count": 22},
            {"path": "tests/test_coupons.py", "count": 14},
        ],
        "directory_concentration": 0.66,
        "tests_invoked": 14,
        "git_status_invoked": 2,
        "git_diff_invoked": 3,
        "pr_referenced": False,
        "assistant_chars": 23410,
        "user_chars": 4218,
        "reasoning_chars": 8104,
        "assistant_to_user_text_ratio": 5.55,
        "user_friction_signals": {"explicit_corrections": 1, "rephrased_retries": 0},
        "last_event_type": "message",
        "final_tool_status": "success",
        "error_concentration_tail": 0.3,
        "events_since_last_user_message": 8,
        "goal": "Implement percentage + flat coupon discount logic with stacking rules.",
        "topics": ["coupon-codes", "discount-logic", "checkout-flow", "edge-cases"],
        "external_systems_touched": [],
        "verification_completeness": "thoroughly_verified",
        "prompt_quality_signal": "well_formed",
        "tasks": [
            {
                "task_id": "t1",
                "intent": "Add Coupon model + apply_coupons function with percentage + flat types",
                "event_range": [0, 287],
                "task_type": "feature_implementation",
                "task_difficulty": {"scope": "few_files", "specification": "clear", "external_dependencies": "none", "verification_ease": "automated", "overall": "moderate"},
                "outcome": "completed",
                "outcome_evidence_event": 287,
                "time_to_first_verified_progress": 178,
            },
            {
                "task_id": "t2",
                "intent": "Handle stacking edge cases (max one percentage + multiple flat)",
                "event_range": [288, 567],
                "task_type": "feature_implementation",
                "task_difficulty": {"scope": "single_file", "specification": "partial", "external_dependencies": "none", "verification_ease": "automated", "overall": "moderate"},
                "outcome": "completed",
                "outcome_evidence_event": 567,
                "time_to_first_verified_progress": 421,
            },
        ],
        "friction_moments": [
            {
                "event_range": [342, 387],
                "task_id": "t2",
                "type": "wrong_abstraction",
                "tool_category": "write",
                "description": "Tried to express stacking rules as a generic priority queue; user asked for a simple if-block.",
                "key_quote": "do we really need a priority queue here?",
                "cost_events": 46,
                "cost_active_minutes": 9.4,
            },
        ],
        "waste_signature": "wrong_abstraction",
        "key_decisions": [
            {
                "event_index": 142,
                "decision": "Decimal arithmetic for all coupon math (no float)",
                "retrospective": "Right — money math + floats = bugs.",
            },
            {
                "event_index": 387,
                "decision": "Replace priority-queue stacking with explicit if/else",
                "retrospective": "Right call after pushback — 12-line if/else handles all 3 stack cases readably.",
            },
        ],
        "dead_ends": [
            {
                "event_range": [342, 387],
                "approach": "heapq.heappush for coupon priority resolution",
                "abandoned_at": 387,
                "lesson": "Premature abstraction. Start with the dumbest implementation that passes tests; abstract only when you have ≥3 cases.",
            },
        ],
        "recurring_environmental_issues": [],
        "user_caught_model_errors": {
            "count": 1,
            "examples": [
                {"event_index": 366, "what_user_caught": "Priority queue was overkill for 3 coupon types"},
            ],
        },
        "counterfactual": "At event 342, if the agent had asked 'should I keep this simple or build for future coupon types?' before introducing heapq, the 46-event abstraction detour would have been avoided.",
        "lesson_for_agent": "When introducing a data structure (priority queue, dispatch table, factory), pause and ask if a 3-case if/else suffices. Default to the simplest thing that works.",
        "lesson_for_user": "",
        "notable": "Good thorough verification — wrote tests for all 7 stacking edge cases. Final coupon logic is 47 lines; tests are 124. Right ratio.",
        "narrative_quality": "high",
    },
    {
        "session_id": "codex:019fe3b7-2c45-7891-bc34-def567890809",
        "agent": "codex",
        "project_path": "/Users/alex/work/acme-tooling",
        "project_label": "work/acme-tooling",
        "git_branch_last": "main",
        "models_used": ["gpt-5.4"],
        "primary_model": "gpt-5.4",
        "started_at": "2026-04-22T16:18:00Z",
        "ended_at": "2026-04-22T17:02:14Z",
        "wall_clock_minutes": 44.2,
        "active_minutes": 38.7,
        "primary_burst_minutes": 38.7,
        "longest_idle_minutes": 1.1,
        "bursts": 1,
        "events_per_active_minute": 6.8,
        "time_of_day_buckets": {"morning": 0, "afternoon": 263, "evening": 0, "night": 0},
        "weekday": "Wednesday",
        "event_count": 263,
        "tool_call_count": 87,
        "user_turn_count": 9,
        "subagent_count": 0,
        "subagent_event_count": 0,
        "subagent_types_spawned": {},
        "tool_call_distribution": {"exec_command": 41, "apply_patch": 18, "read_stdin": 14, "write_stdin": 14},
        "tool_category_distribution": {"shell": 41, "write": 18, "other": 28},
        "tool_error_rate": 0.184,
        "tool_error_classes": {"nonzero_exit": 14, "permission_denied": 2},
        "most_repeated_tool_call": {"tool": "exec_command", "input_hash": "ababcdcdef", "count": 6, "input_preview": "{\"command\": \"python\"}"},
        "unique_files_touched": 6,
        "top_files_touched": [
            {"path": "scripts/migrate_users.py", "count": 12},
        ],
        "directory_concentration": 0.78,
        "tests_invoked": 0,
        "git_status_invoked": 1,
        "git_diff_invoked": 1,
        "pr_referenced": False,
        "assistant_chars": 11214,
        "user_chars": 1820,
        "reasoning_chars": 4128,
        "assistant_to_user_text_ratio": 6.16,
        "user_friction_signals": {"explicit_corrections": 3, "rephrased_retries": 1},
        "last_event_type": "tool_result",
        "final_tool_status": "error",
        "error_concentration_tail": 1.6,
        "events_since_last_user_message": 14,
        "goal": "Write a one-time migration script to backfill `created_at` on legacy user records.",
        "topics": ["migration-script", "user-backfill", "python-bare", "macos-path"],
        "external_systems_touched": [],
        "verification_completeness": "claimed_only",
        "prompt_quality_signal": "well_formed",
        "tasks": [
            {
                "task_id": "t1",
                "intent": "Write scripts/migrate_users.py that backfills missing created_at from audit_log",
                "event_range": [0, 262],
                "task_type": "infrastructure",
                "task_difficulty": {"scope": "single_file", "specification": "clear", "external_dependencies": "one", "verification_ease": "partial", "overall": "moderate"},
                "outcome": "stuck_at_end",
                "outcome_evidence_event": 262,
                "time_to_first_verified_progress": -1,
            },
        ],
        "friction_moments": [
            {
                "event_range": [12, 67],
                "task_id": "t1",
                "type": "tool_error_loop",
                "tool_category": "shell",
                "description": "Ran `python scripts/migrate_users.py` 6 times, each failing with 'command not found: python'. macOS only has python3.",
                "key_quote": "zsh: command not found: python",
                "cost_events": 56,
                "cost_active_minutes": 12.4,
            },
        ],
        "waste_signature": "tool_error_loop",
        "key_decisions": [],
        "dead_ends": [],
        "recurring_environmental_issues": [
            {
                "description": "macOS doesn't ship `python` — only `python3`. Add `alias python=python3` to ~/.zshrc, OR start scripts with `#!/usr/bin/env python3` shebang.",
                "occurrences": [12, 18, 24, 31, 47, 58, 67],
            },
        ],
        "user_caught_model_errors": {
            "count": 1,
            "examples": [
                {"event_index": 67, "what_user_caught": "Use python3, not python — macOS doesn't have a 'python' command"},
            ],
        },
        "counterfactual": "If the prompt or AGENTS.md had specified 'this machine uses python3, not python', the 56-event tool_error_loop at events 12-67 would have been zero.",
        "lesson_for_agent": "On macOS, default to `python3` invocation. Never assume `python` is on PATH.",
        "lesson_for_user": "Add `alias python=python3` to your ~/.zshrc once — eliminates this for every Codex session on macOS.",
        "notable": "This same 'python not found' pattern hits every Codex session on this machine. Single-line shell alias eliminates it forever.",
        "narrative_quality": "high",
    },
    {
        "session_id": "claude:f3e4d5c6-b7a8-9012-3456-789abcdef810",
        "agent": "claude",
        "project_path": "/Users/alex/work/acme-api",
        "project_label": "work/acme-api",
        "git_branch_last": "fix/db-pool-leak",
        "models_used": ["claude-opus-4-7"],
        "primary_model": "claude-opus-4-7",
        "started_at": "2026-04-26T10:18:00Z",
        "ended_at": "2026-04-26T12:42:18Z",
        "wall_clock_minutes": 144.3,
        "active_minutes": 132.8,
        "primary_burst_minutes": 132.8,
        "longest_idle_minutes": 1.8,
        "bursts": 1,
        "events_per_active_minute": 8.2,
        "time_of_day_buckets": {"morning": 612, "afternoon": 477, "evening": 0, "night": 0},
        "weekday": "Sunday",
        "event_count": 1089,
        "tool_call_count": 348,
        "user_turn_count": 23,
        "subagent_count": 1,
        "subagent_event_count": 124,
        "subagent_types_spawned": {"explore": 1},
        "tool_call_distribution": {"Bash": 92, "Read": 84, "Edit": 38, "Grep": 41, "Glob": 18},
        "tool_category_distribution": {"shell": 92, "read": 125, "write": 38, "delegation": 4, "other": 89},
        "tool_error_rate": 0.041,
        "tool_error_classes": {"tool_error": 14},
        "most_repeated_tool_call": {"tool": "Bash", "input_hash": "feedfacc01", "count": 8, "input_preview": "{\"command\": \"docker compose logs api --tail 200\"}"},
        "unique_files_touched": 38,
        "top_files_touched": [
            {"path": "src/db/session.py", "count": 24},
            {"path": "src/api/middleware.py", "count": 14},
            {"path": "Dockerfile", "count": 8},
        ],
        "directory_concentration": 0.51,
        "tests_invoked": 18,
        "git_status_invoked": 4,
        "git_diff_invoked": 6,
        "pr_referenced": True,
        "assistant_chars": 41204,
        "user_chars": 7218,
        "reasoning_chars": 16482,
        "assistant_to_user_text_ratio": 5.71,
        "user_friction_signals": {"explicit_corrections": 2, "rephrased_retries": 1},
        "last_event_type": "message",
        "final_tool_status": "success",
        "error_concentration_tail": 0.4,
        "events_since_last_user_message": 8,
        "goal": "Diagnose + fix the connection pool leak that's spiking on the prod /refunds endpoint.",
        "topics": ["db-pool-leak", "sqlalchemy", "production-bug", "observability"],
        "external_systems_touched": ["github", "aws"],
        "verification_completeness": "thoroughly_verified",
        "prompt_quality_signal": "well_formed",
        "tasks": [
            {
                "task_id": "t1",
                "intent": "Reproduce the pool leak locally with same load pattern as prod",
                "event_range": [0, 387],
                "task_type": "debugging",
                "task_difficulty": {"scope": "cross_module", "specification": "exploratory", "external_dependencies": "multiple", "verification_ease": "partial", "overall": "hard"},
                "outcome": "completed",
                "outcome_evidence_event": 387,
                "time_to_first_verified_progress": 287,
            },
            {
                "task_id": "t2",
                "intent": "Identify the leak source via SQLAlchemy event listeners + add a regression test",
                "event_range": [388, 891],
                "task_type": "debugging",
                "task_difficulty": {"scope": "few_files", "specification": "partial", "external_dependencies": "one", "verification_ease": "automated", "overall": "hard"},
                "outcome": "completed",
                "outcome_evidence_event": 891,
                "time_to_first_verified_progress": 612,
            },
            {
                "task_id": "t3",
                "intent": "Patch the leaking get_refund_by_id (missing session.close in error path) + verify in staging",
                "event_range": [892, 1088],
                "task_type": "bug_fix",
                "task_difficulty": {"scope": "single_file", "specification": "clear", "external_dependencies": "one", "verification_ease": "automated", "overall": "moderate"},
                "outcome": "completed",
                "outcome_evidence_event": 1088,
                "time_to_first_verified_progress": 987,
            },
        ],
        "friction_moments": [
            {
                "event_range": [142, 198],
                "task_id": "t1",
                "type": "exploration_drift",
                "tool_category": "shell",
                "description": "Investigated 3 unrelated middleware files before realizing the leak was in the repository layer, not middleware.",
                "key_quote": "wait, this is in middleware.py, but the trace showed src/db/session.py?",
                "cost_events": 57,
                "cost_active_minutes": 9.8,
            },
        ],
        "waste_signature": "exploration_drift",
        "key_decisions": [
            {
                "event_index": 412,
                "decision": "Use SQLAlchemy event listeners (after_checkin, before_checkout) to instrument pool usage",
                "retrospective": "Excellent — gave clean per-request connection lifecycle visibility that pinpointed the leak in 200 events.",
            },
            {
                "event_index": 612,
                "decision": "Reproduce via integration test (locust 50 concurrent → check pool depth) rather than manual",
                "retrospective": "Right call — automated repro means future regressions get caught.",
            },
        ],
        "dead_ends": [
            {
                "event_range": [142, 198],
                "approach": "Investigate middleware.py for unclosed sessions",
                "abandoned_at": 198,
                "lesson": "When a stack trace points to db/session.py, don't get distracted by 'related' middleware files. Follow the trace, not adjacency.",
            },
        ],
        "recurring_environmental_issues": [],
        "user_caught_model_errors": {
            "count": 1,
            "examples": [
                {"event_index": 187, "what_user_caught": "Following adjacency rather than the actual error trace"},
            ],
        },
        "counterfactual": "At event 142, reading the actual error stack trace (one Read of the prod log) before guessing at middleware would have skipped 57 events of unrelated investigation.",
        "lesson_for_agent": "When debugging a production issue with a stack trace, the trace IS the contract. Follow it precisely; don't generalize to 'related' code.",
        "lesson_for_user": "Add a `tessera-rule` that flags when an investigation diverges from the actual stack trace — would have caught this earlier.",
        "notable": "Best debugging session of the week — clear repro, instrumentation, fix, regression test, staging verify. The investigation was 80 minutes; the fix itself was 4 lines.",
        "narrative_quality": "high",
    },
]


# ---------- Synthesis ----------
# Hand-crafted to reference the narratives via ref tokens S001..S010.

# Map each session to its ref
REFS = {s["session_id"]: f"S{i:03d}" for i, s in enumerate(SESSIONS, start=1)}
REFS_REV = {v: k for k, v in REFS.items()}

OBSERVATIONS = [
    {
        "title": "Test environment setup is the #1 friction source — same pattern in 4 of 10 sessions",
        "claim": "Across 4 distinct sessions, the agent burned 12-56 events on missing test config: STRIPE_WEBHOOK_SECRET (S001), live-key-in-test (S002), `python` not on PATH on macOS (S009), database-locked migrations (S004). Each is a one-line config fix that would eliminate the entire class of error.",
        "evidence_refs": ["S001", "S002", "S004", "S009"],
        "supporting_count": 4,
        "interpretation": "Test environment 'just works' for humans because we set it up manually once. Agents start fresh every session and rediscover each constraint. The fix isn't smarter agents — it's surfacing the constraint as code (CLAUDE.md, pyproject.toml [tool.pytest_env], shell aliases). Cross-session pattern: 4 different sessions, 4 different constraints, all in the same shape.",
        "next_action": "Set up `pytest-env` in acme-api + acme-checkout pyproject.toml with all required test secrets (use dummy values: `whsec_test_dummy`, `sk_test_dummy`, etc.). Add `alias python=python3` to ~/.zshrc. One evening of setup eliminates the dominant friction class for the rest of the year.",
        "confidence": "high",
        "category": "environmental",
        "trend": "stable",
        "continues": None,
    },
    {
        "title": "Blind retry without changing the input — 2 sessions, 4+ hours wasted",
        "claim": "S005 (mobile SDK upgrade) ran `npx expo install --fix` 14 times in 4 hours hoping the peer-deps would self-resolve. S004 (refund migration) ran `alembic upgrade head` 6 times against a locked database. Both eventually resolved by reading docs / fixing config.",
        "evidence_refs": ["S005", "S004"],
        "supporting_count": 2,
        "interpretation": "Both cases share a structure: agent runs a command, it fails, agent runs the same command again. After 2-3 retries, the issue is never the command's flakiness — it's missing context. The agent needs a heuristic: 'after N identical retries, stop and read docs / change strategy'.",
        "next_action": "The reflect-coach hook already detects this via the `retry_without_change` rule (≥3 identical retries triggers a nudge). Confirm the hook is installed in your Claude Code; install if not: `cd tessera-live && /plugin add .`",
        "confidence": "high",
        "category": "tooling",
        "trend": "new",
        "continues": None,
    },
    {
        "title": "Late-night sessions correlate with low-quality work — strong signal even on 1 session",
        "claim": "S005 (Saturday 10pm-1:30am) produced this week's longest tool_error_loop (203 events / 38 min on Pod resolution) and only blind_retry waste signature in the dataset. The other 9 sessions were morning/afternoon and showed varied, productive patterns.",
        "evidence_refs": ["S005"],
        "supporting_count": 1,
        "interpretation": "Single-session signal so weak confidence — but the contrast is sharp. Late-night sessions on framework upgrades may be the worst-case combo: high cognitive load + low patience for reading docs first. Easy enough to track over more weeks.",
        "next_action": "Don't start framework upgrades after 9pm. If you must, start by reading the official changelog (one Read call) before any install command.",
        "confidence": "low",
        "category": "workflow",
        "trend": "new",
        "continues": None,
    },
    {
        "title": "Subagent over-delegation on small codebases — 487 events for what 3 reads would answer",
        "claim": "S007 spawned 4 parallel exploration subagents on a 19-file middleware folder; the existing RateLimiter pattern was missed. 145 wasted events. The session that did it RIGHT (S003) used subagents for a 9-file PR review in parallel — appropriate scale, saved 25 minutes.",
        "evidence_refs": ["S007", "S003"],
        "supporting_count": 2,
        "interpretation": "Subagents shine for genuinely-parallel work on broad codebases. They flop on 'I'm not sure where to look' on small codebases — context lossy summaries replace what direct Read would give you. Rule of thumb: <50 files = direct Read+Grep; >50 files OR genuinely parallel = subagents.",
        "next_action": "Add to acme-api/CLAUDE.md: 'middleware patterns: src/api/middleware.py — use the existing RateLimiter base class for new throttling middleware. For codebase exploration on this repo (<25 files in any single dir), prefer direct Read+Grep over subagent delegation.'",
        "confidence": "medium",
        "category": "tooling",
        "trend": "new",
        "continues": None,
    },
    {
        "title": "Stack-trace-driven debugging vs adjacency-driven debugging — clean signal in S010",
        "claim": "S010 (DB pool leak) initially investigated middleware.py because it was 'related to the API' even though the stack trace pointed at src/db/session.py. 57 events of dead-end exploration before pivoting to follow the trace.",
        "evidence_refs": ["S010"],
        "supporting_count": 1,
        "interpretation": "When a stack trace exists, it's the highest-precision signal in debugging. Adjacency reasoning ('middleware is related to APIs') is lower-precision. The agent reverts to adjacency when the trace is in a less-familiar module. Worth flagging because S010 was otherwise the best debugging session of the week — this was its only friction.",
        "next_action": "Add a personal habit: when investigating a production bug, the FIRST file read should be the one named in the stack trace, not 'related' files. Ask the agent to do this explicitly: 'Start by reading the file named in the stack trace.'",
        "confidence": "medium",
        "category": "workflow",
        "trend": "new",
        "continues": None,
    },
    {
        "title": "Explicit verification asks consistently improve outcome quality",
        "claim": "S001 (Stripe), S006 (S3 cleanup), S008 (coupon stacking), S010 (pool leak) all did thorough verification (test runs + dry-runs + staging). They had 0-1 friction moments each. Sessions without explicit verification (S002 e2e tests claimed_only, S009 migration script claimed_only) shipped issues the user caught.",
        "evidence_refs": ["S001", "S006", "S008", "S010", "S002", "S009"],
        "supporting_count": 6,
        "interpretation": "The verification_completeness field is a strong outcome predictor on this dataset. Sessions tagged 'thoroughly_verified' cleared with minimal user-caught errors; 'claimed_only' sessions had user-caught errors. This is a habit-level signal, not a model-capability one.",
        "next_action": "Make 'verify before claiming complete' explicit in the prompt: 'After you believe the task is done, run the relevant test/lint/build BEFORE saying you're done. If you can't verify, say so explicitly.' Add this to your global CLAUDE.md.",
        "confidence": "high",
        "category": "prompting",
        "trend": "stable",
        "continues": None,
    },
]

QUICK_WINS = [
    {
        "fix": "Add `pytest-env` to acme-checkout/pyproject.toml + populate test secrets (whsec_test_dummy, sk_test_dummy). Eliminates the test-env-discovery loop in every webhook session.",
        "affected_sessions": 2,
        "evidence_refs": ["S001", "S002"],
    },
    {
        "fix": "Add `alias python=python3` to ~/.zshrc. Eliminates 'command not found: python' across every Codex session on macOS.",
        "affected_sessions": 1,
        "evidence_refs": ["S009"],
    },
    {
        "fix": "Edit your code-review skill prompt: change `git diff main...origin/BRANCH` to `git fetch origin main && git diff origin/main...origin/BRANCH`. One line, eliminates the stale-main blind_retry pattern.",
        "affected_sessions": 1,
        "evidence_refs": ["S003"],
    },
    {
        "fix": "Add to acme-api/CLAUDE.md: 'Stripe error handling: use `src/payments/decorators.StripeRetry`. Migrations: alembic autogen + always include downgrade(). DB locked errors: stop dev server first.'",
        "affected_sessions": 1,
        "evidence_refs": ["S004"],
    },
    {
        "fix": "Add to acme-mobile/AGENTS.md: 'For SDK upgrades: read expo.dev/changelog/sdk-N FIRST. Never run `expo install --fix` more than 2 times — pin manually after that.'",
        "affected_sessions": 1,
        "evidence_refs": ["S005"],
    },
]

PER_PROJECT = [
    {
        "project": "work/acme-checkout",
        "session_count": 4,
        "headline": "Stripe integration is the dominant work area — productive but consistently friction-loaded by missing test environment setup.",
        "biggest_friction": "tool_error_loop on STRIPE_WEBHOOK_SECRET (S001) and live-key-in-test confusion (S002). Pattern: agent assumes test env is fully bootstrapped; it isn't. Fix is one-time: pytest-env in pyproject.toml.",
    },
    {
        "project": "work/acme-api",
        "session_count": 3,
        "headline": "Three sessions, three different waste patterns — exploration_drift, over_delegation, exploration_drift. The codebase is small enough that subagents and exhaustive exploration are usually overkill.",
        "biggest_friction": "Reimplementing patterns that already exist (S004 StripeRetry, S007 RateLimiter). A short CLAUDE.md mapping common patterns to their location would eliminate this.",
    },
    {
        "project": "work/acme-mobile",
        "session_count": 1,
        "headline": "Saturday late-night SDK upgrade went sideways — 4 hours of blind retry on peer-deps that needed manual pinning.",
        "biggest_friction": "blind_retry on `expo install --fix`. Context: framework upgrades + late hours + no docs-first habit.",
    },
    {
        "project": "work/acme-tooling",
        "session_count": 2,
        "headline": "One-off scripts. Cleanest sessions of the week — clear scope, dry-run-first habits, zero friction. The exception was S009 (python vs python3).",
        "biggest_friction": "macOS python/python3 alias missing. Single-line fix.",
    },
]

NOTES = (
    "Demo dataset — fictional persona 'Alex at Acme Payments' with 10 fabricated sessions covering varied friction patterns. "
    "All session_ids, project paths, file names, and quotes are synthetic. "
    "Run `tessera run` against your own ~/.claude/projects/, ~/.codex/sessions/, ~/.gemini/tmp/ to see real findings from your own work."
)


def build_synthesis() -> dict:
    return {
        "headline": "Test environment setup is the #1 friction source this week — 4 of 10 sessions burned 12-56 events on the same class of one-line config issues.",
        "if_you_do_one_thing_this_week": "Add `pytest-env` to acme-checkout/pyproject.toml with dummy test secrets (whsec_test_dummy, sk_test_dummy) — eliminates the dominant friction class across every Stripe-related session, both Claude and Codex.",
        "observations": OBSERVATIONS,
        "quick_wins": QUICK_WINS,
        "per_project": PER_PROJECT,
        "meta": {
            "input_sessions": len(SESSIONS),
            "model": "demo (fabricated)",
            "generated_at": "2026-04-27T09:00:00.000000+00:00",
            "had_prior_context": False,
            "fabricated_ref_count": 0,
            "notes": NOTES,
            "filter_context": {
                "lookback_days": 7,
                "min_events": 20,
                "in_window": 12,
                "dropped_short": 2,
                "dropped_slash": 0,
                "dropped_undated": 0,
                "total_raw_top_level_sessions": 14,
                "narratives_in_synthesis": len(SESSIONS),
            },
            "timeline": {
                "new": 5,
                "continuing": 1,
                "improving": 0,
                "stable": 1,
                "worsening": 0,
                "resolved_count": 2,
                "resolved": [],
                "prior_run_timestamp": "2026-04-20T09:00:00",
            },
            "run_slug": "demo-2026-04-27",
        },
    }


def main():
    # Add evidence_sessions to each observation/quick_win for renderer
    syn = build_synthesis()
    for obs in syn["observations"]:
        obs["evidence_sessions"] = [REFS_REV[r] for r in obs["evidence_refs"]]
    for qw in syn["quick_wins"]:
        qw["evidence_sessions"] = [REFS_REV[r] for r in qw["evidence_refs"]]

    (OUT / "synthesis.json").write_text(
        json.dumps(syn, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    for s in SESSIONS:
        path = NARRATIVES_DIR / (s["session_id"].replace(":", "__") + ".json")
        path.write_text(json.dumps(s, indent=2, ensure_ascii=False), encoding="utf-8")

    print(f"Wrote {len(SESSIONS)} narratives to {NARRATIVES_DIR}")
    print(f"Wrote synthesis.json to {OUT}")


if __name__ == "__main__":
    main()
